server:
  port: 9090

spring:
  application:
    name: springboot

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: root
    url: jdbc:mysql://localhost:3306/lightning?serverTimezone=GMT%2b8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.example.springboot.entity